# Generated by Django 4.2.16 on 2024-09-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="etape_suivante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.etape",
            ),
        ),
        migrations.AlterField(
            model_name="etape",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="high_level.machine"
            ),
        ),
        migrations.AlterField(
            model_name="etape",
            name="quantite_ressource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.quantiteressource",
            ),
        ),
        migrations.AlterField(
            model_name="quantiteressource",
            name="ressource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="high_level.ressource"
            ),
        ),
    ]
