# Generated by Django 5.1.1 on 2025-01-04 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="ressource",
        ),
    ]
